# Generated by Django 5.1.1 on 2024-12-31 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_alter_customuser_managers_alter_customuser_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="traveller",
            name="pickup_point",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="travellers",
                to="bookings.pickuppoint",
            ),
        ),
    ]
